Teste de implementação em phyton do Algoritmo Genético.
Obs.:

# Algoritmo Genético
## Para o problema das 8 rainhas

## Importações

In [1]:
# Manipulação de dados
import numpy as np
#import pandas as pd

# Geração de números aleatórios
import random

In [2]:
#VT = np.array([4,8,2,7,3,1,5,6])
VT = np.array([4,8,2,7,3,7,5,4])

VT

array([4, 8, 2, 7, 3, 7, 5, 4])

## Funções Auxiliares - Problema

### Converte Vetor em Tabuleiro

In [3]:
def converte_tabuleiro(VT):
    '''
    Recebe um vetor representando um tabuleiro
    com N rainhas, uma por coluna e retorna
    uma lista de lista de 0 e 1 representando
    um tabuleiro com as rainhas.
    '''
    N = len(VT)

    L = [0]*N
    T = []
    for i in range(N):
        T += [L.copy()]

    for lin in range(N):
        for col in range(N):
            if lin+1 == VT[col]:
                T[lin][col] = 1

    return T

In [4]:
converte_tabuleiro(VT)

[[0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 1, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 1, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 1, 0, 1, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0]]

### Calcula custo (Fitness)

In [5]:
def __conta_ataques_linhas(VT):
    '''
    Função que recebe um Vetor-Tabuleiro e
    retorna o número de pares de rainhas se
    atacando mutuamente nas linhas.
    '''
    ataques = 0
    N = len(VT)
    for col1 in range(N):
        lin1 = VT[col1]
        for col2 in range(col1+1, N):
            lin2 = VT[col2]
            if lin1==lin2:
                ataques +=1

    return ataques

In [6]:
__conta_ataques_linhas(VT)

2

In [7]:
def __conta_ataques_diagonais(VT):
    '''
    Função que recebe um Vetor-Tabuleiro e
    retorna o número de pares de rainhas se
    atacando mutuamente nas diagonais.
    '''
    ataques = 0
    N = len(VT)

    for col1 in range(N):
        lin1 = VT[col1]
        for col2 in range(col1+1, N):
            lin2 = VT[col2]

            # diferenças entre as linhas e colunas
            d1 = lin1-col1
            d2 = lin2-col2

            # somas das linhas e colunas
            s1 = lin1+col1
            s2 = lin2+col2

            # condições para ataques nas diagonais
            if d1==d2 or s1==s2:
                ataques +=1
                #print(f'({lin1},{col1+1}) ({lin2},{col2+1}) -->', ataques,
                #      '<--', f'  -({d1:2},{d2:2})  +({s1:2},{s2:2})')

    return ataques

In [8]:
converte_tabuleiro(VT)

[[0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 0],
 [0, 0, 0, 0, 1, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 1],
 [0, 0, 0, 0, 0, 0, 1, 0],
 [0, 0, 0, 0, 0, 0, 0, 0],
 [0, 0, 0, 1, 0, 1, 0, 0],
 [0, 1, 0, 0, 0, 0, 0, 0]]

In [9]:
__conta_ataques_diagonais(VT)

4

In [10]:
def conta_ataques(VT):
    '''
    Função que recebe um Vetor-Tabuleiro e
    retorna o número de pares de rainhas se
    atacando mutuamente nas linhas e diagonais.
    '''
    ataques  = __conta_ataques_linhas(VT)

    ataques += __conta_ataques_diagonais(VT)

    return ataques

In [11]:
VT = [1,2,3,4,5,6,7,8]

In [12]:
conta_ataques(VT)

28

### Gera vizinhos

In [13]:
def gera_vizinhos(VT):
    '''
    Gera todos os vizinhos possíveis,
    variando uma rainha de cada vez.
    '''
    N = len(VT)
    for col in range(N):
        for lin in range(N):
            # se nao existe rainha naquela linha,
            # entao gera estado vizinho.
            linha = lin+1
            if linha != VT[col]:
                vizinho   = VT.copy()
                vizinho[col] = linha

                yield vizinho


### Gera tuplas custos

In [14]:
def gera_tuplas_custos(Populacao):
    '''
    Gera tuplas com os custos de todos os individuos da populacao.
    '''
    TuplasCustos = []
    for individuo in Populacao:
        ataques = conta_ataques(individuo)

        TuplasCustos += [(ataques, individuo)]

    return TuplasCustos


In [ ]:
Populacao = gera_vizinhos(VT)
Tuplas = gera_tuplas_custos(Populacao)
Tuplas

In [ ]:
sorted(Tuplas, key=lambda k: k[0])

## Funções Auxiliares - AG

### Mutação

In [18]:
def mutacao(VT, p_mutacao=0.15):

    VT_mutated = VT.copy()

    N = len(VT)
    p = np.random.rand()

    if p < p_mutacao:
        col   = np.random.randint(0,N)    # indice da coluna (base-0)
        linha = np.random.randint(1,N+1)  # valor da linha   (base-1)

        VT_mutated[col] = linha
        #print(col+1, linha)

    return VT_mutated

In [19]:
VT2 = mutacao(VT)
VT, VT2, VT != VT2

([1, 2, 3, 4, 5, 6, 7, 8], [1, 2, 3, 4, 3, 6, 7, 8], True)

### Crossover

In [20]:
def crossover(Parent1, Parent2):

    N = len(Parent1)

    # ponto de corte
    c = np.random.randint(1, N-1)

    # crossover no ponto de corte
    # gerando dois filhos
    child1 = Parent1[:c] + Parent2[c:]
    child2 = Parent2[:c] + Parent1[c:]

    return child1, child2

In [21]:
VT1 = [1,1,1,1,1,1,1,1]
VT2 = [2,2,2,2,2,2,2,2]

In [22]:
crossover(VT1,VT2)

([1, 2, 2, 2, 2, 2, 2, 2], [2, 1, 1, 1, 1, 1, 1, 1])

### Seleciona pais

In [23]:
def selecao(Populacao):
    Candidato1 = random.choice(Populacao)
    Candidato2 = random.choice(Populacao)

    a1 = conta_ataques(Candidato1)
    a2 = conta_ataques(Candidato2)
    #print(a1,a2)

    # eleito o candidato com menor custo
    eleito = Candidato1 if a1<=a2 else Candidato2

    return eleito

In [24]:
selecao([VT1,VT2])

[2, 2, 2, 2, 2, 2, 2, 2]

### Gera Indivíduo

In [25]:
def gera_individuo(n_cols):
    # individuo é um Vetor (N) em que cada posicação
    # representa uma coluna indicando as respectivas
    # linhas ocupadas pelas rainhas em um tabuleiro (NxN).

    # VT = [low, high) x n_cols

    VT = np.random.randint(low=1, high=n_cols+1, size=n_cols)
    return VT

In [26]:
N=8
gera_individuo(N)

array([8, 2, 7, 3, 8, 6, 1, 8])

### Gera População

In [27]:
def gera_populacao_inicial(N, tam_pop):
    # N:       tamanho do tabuleiro (NxN)
    # tam_pop: tamanho da população
    populacao = []
    for _ in range(tam_pop):
        individuo = gera_individuo(N)

        populacao.append(individuo)

    return populacao

[array([7, 3, 8, 6, 8, 6, 3, 6]),
 array([5, 8, 8, 6, 7, 4, 5, 6]),
 array([2, 1, 5, 5, 7, 7, 1, 1]),
 array([4, 4, 6, 2, 5, 3, 5, 1]),
 array([7, 1, 3, 3, 6, 8, 5, 6]),
 array([8, 3, 7, 6, 7, 8, 5, 3]),
 array([6, 7, 1, 3, 6, 6, 6, 8]),
 array([5, 1, 4, 5, 6, 2, 8, 7]),
 array([3, 8, 4, 1, 5, 7, 3, 3]),
 array([4, 6, 4, 8, 2, 6, 4, 6])]

## Algoritmo Genético - Implementação

In [ ]:
# 1) Randomly initialize populations p
# 2) Compute fitness of population
# 3) Until convergence repeat:
#       a) Select parents from population
#       b) Crossover and generate new population
#       c) Perform mutation on new population
#       d) Calculate fitness for new population

In [28]:
def algoritmo_genetico():
    # pseudo-código:

    # START
    N = 8
    tam_pop = 10
    fitness = gera_tuplas_custos # função fitness

    # Generate the initial population
    Populacao = gera_populacao_inicial(N, tam_pop)

    # Compute fitness - apenas em caso de elitismo
    #custosPopulacao = fitness(Populacao)

    # REPEAT
    while (True):
        #     Selection
        selecao(Populacao)
        #     Crossover
        #     Mutation
        #     Compute fitness
        # UNTIL population has converged
    # STOP

    # coloque seu código aqui
    pass